"""
Aggregate analysis script for cross-session learning curves.

This script loads session summary data (generated by 01_batch_session_analysis.py)
and plots metrics across sessions for each subject.
"""

import argparse
import logging
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import sys

# Ensure src is in path
sys.path.append(str(Path(__file__).resolve().parents[2] / "src"))

from visdetect_photom.viz import plotting

logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")

def plot_learning_curves(df: pd.DataFrame, output_dir: Path):
    """
    Plot learning curves for each subject.
    """
    subjects = df['subject_id'].unique()
    for subj in subjects:
        subj_df = df[df['subject_id'] == subj].sort_values('session_date')
        
        plt.figure(figsize=(10, 6))
        # Example: Plot d-prime over sessions
        if 'd_prime' in subj_df.columns:
            plt.plot(subj_df['session_date'], subj_df['d_prime'], marker='o')
            plt.title(f"Learning Curve (d') - {subj}")
            plt.xlabel("Session")
            plt.ylabel("d'")
            plt.xticks(rotation=45)
            plt.tight_layout()
            plt.savefig(output_dir / f"{subj}_learning_curve.png")
            plt.close()

def main():
    parser = argparse.ArgumentParser(description="Aggregate learning analysis.")
    parser.add_argument("--input_dir", type=str, default="E:/python_analysis/git_repos/vis_detect_analysis_Apr2023/FIGURES/batch_output", help="Directory containing session summaries.")
    parser.add_argument("--output_dir", type=str, default="E:/python_analysis/git_repos/vis_detect_analysis_Apr2023/FIGURES/learning_curves", help="Directory to save aggregated plots.")
    
    args = parser.parse_args()
    
    input_path = Path(args.input_dir)
    output_path = Path(args.output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Load all session summaries
    # Assuming 01_batch_session_analysis.py saves a CSV per session or a master CSV
    # For this template, let's assume we look for a master summary file or glob individual ones
    
    # Placeholder: Create a dummy dataframe if no data exists yet
    # df = pd.read_csv(input_path / "all_sessions_summary.csv")
    logging.info("Loading session summaries...")
    
    # Logic to aggregate data goes here
    
    logging.info("Generating learning curves...")
    # plot_learning_curves(df, output_path)

if __name__ == "__main__":
    main()
